### ISSUE TITLE
Draft - Single Shot Connection

### ISSUE THREAD

**Issue by LeonMatthesKDAB** [KDAB/KDBindings#21]
A single shot connection could possibly be implemented by creating a binding that captures its own ConnectionHandle and disconnects it when the signal is emitted.

Open question: How to capture the ConnectionHandle in the slot itself?

**Comment by phyBrackets** [comment]
I'm a bit confused about this, don' we need special method for single shot connection, like `singleShotConnect` ? that gets disconnected after emit, which could be easily implemented just by having a set flag `isSingleShot` in `singleShotConnect` and each time when `emit` gets called, it should check that emit was on a single shot connection and if that's the case immediately disconnects it? Don't need to get around connection handle.

**Comment by LeonMatthesKDAB** [comment]
That should work as well. I was just thinking that something like this should maybe be possible:

```cpp
mySignal.connect([](const auto &handle) {
    // do thing
    handle.disconnect();
});
```

More of a thought experiment than anything substantial. An approach like that wouldn't need another `connect` function and seems kind of elegantly recursive almost.
But it's also incompatible with the current connect function I think, so not too much point in it.

Introducing a `singleshotConnect` function definitely works as well, so that's the more likely route to go down.

**Comment by LeonMatthesKDAB** [comment]
The basics of reflective connections were layed out in #23, so we may want to revisit this idea :)

**Comment by LeonMatthesKDAB** [comment]
Complete as of #70
