### ISSUE TITLE
Use signal and slots in QML/Javascript

### ISSUE THREAD

**Issue by reg31** [KDAB/KDBindings#55]
Hi,

As a developer it would be nice to be able to connect the signals to Javascript functions in Qt.

**Comment by LeonMatthesKDAB** [comment]
Hi,
thank you for your interest in KDBindings and for taking the time to open an issue with your suggestion.

Unfortunately I don't quite understand your use-case.
Are you using Qt together with KDBindings? If so, why?
A big part of the reason KDBindings exists is that it's useful in environments where you want Qt features, but can't use Qt directly.

So why can't you just use Qt signals/slots for your use-case?

Happy to hear more about this :)

**Comment by LeonMatthesKDAB** [comment]
Hm, okay. And now you're trying to replace the NOTIFY signal with a `KDBindings::Signal`?

I honestly have no idea how that could be hooked up to QML :thinking:
And it may not be possible without modifying the QML Engine itself.

**Comment by reg31** [comment]
No problem, at least it works great between c++ object.

Good job

**Comment by LeonMatthesKDAB** [comment]
Out of scope for now.
If there's a more concrete plan to make this work, feel free to re-open.
