### ISSUE TITLE
Clazy never fails CI

### ISSUE THREAD

**Issue by LeonMatthesKDAB** [KDAB/KDBindings#64]
Even if clazy generates warnings in CI the runner isn't considered to have failed.
How do we fix this?

**Comment by seanharmer** [comment]
@winterz Any ideas please?

**Comment by LeonMatthesKDAB** [comment]
As clazy is loaded as a dynamic library into clang, it seems we can solve this by simply passing `-Werror` to clang...

I'll open a PR to enable this in our CI to confirm it works.

**Comment by LeonMatthesKDAB** [comment]
Aha, confirmed, it works: https://github.com/KDAB/KDBindings/actions/runs/9362653392/job/25771805019

@winterz can you please approve #73, which enables this in our CI.

**Comment by dantti** [comment]
hmm interesting I think we had this issue in another repo, but I think I did not manage to find the fix, now I need to find which repo it was :)
