### ISSUE TITLE
Property: add getter to know whether a property can be assigned to or not

### ISSUE THREAD

**Issue by lemirep** [KDAB/KDBindings#74]
When a property is assigned a binding, trying to assign a value or another binding to it will result in an exception.

Having a small getter e.g `isBinding()` would be a nice convenience to allow users to check whether reassigning to a property is safe or not without having to try/catch.

**Comment by seanharmer** [comment]
Sounds good to me. Maybe `hasBinding()` or `hasBindingAttached()`?

**Comment by LeonMatthesKDAB** [comment]
Done as of #75
