### ISSUE TITLE
Support singleshot connection

### ISSUE THREAD

**Issue by reg31** [KDAB/KDBindings#97]
It would be nice to have a convenient single shot connection.

https://www.kdab.com/single-shot-connections/

**Comment by seanharmer** [comment]
This should be quite straightforward to do now that we have [Signal::connectReflective](https://github.com/KDAB/KDBindings/blob/efb54c58c3c2fce280d7089617935ec265fe4e2d/src/kdbindings/signal.h#L358)

**Comment by seanharmer** [comment]
Done in #98
